//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param text (optional) 
     * @return OK
     */
    generateAudioFromText(text: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/Admin/generateAudio?";
        if (text === null)
            throw new Error("The parameter 'text' cannot be null.");
        else if (text !== undefined)
            url_ += "text=" + encodeURIComponent("" + text) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGenerateAudioFromText(_response);
        });
    }

    protected processGenerateAudioFromText(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param text (optional) 
     * @return OK
     */
    generateImageFromText(text: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/Admin/generateImage?";
        if (text === null)
            throw new Error("The parameter 'text' cannot be null.");
        else if (text !== undefined)
            url_ += "text=" + encodeURIComponent("" + text) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGenerateImageFromText(_response);
        });
    }

    protected processGenerateImageFromText(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    unreadAllFortunes(): Promise<void> {
        let url_ = this.baseUrl + "/Admin/unreadAllFortunes";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUnreadAllFortunes(_response);
        });
    }

    protected processUnreadAllFortunes(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param fortunesToCreate (optional) 
     * @return OK
     */
    createFortunes(fortunesToCreate: number | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Fortune/create?";
        if (fortunesToCreate === null)
            throw new Error("The parameter 'fortunesToCreate' cannot be null.");
        else if (fortunesToCreate !== undefined)
            url_ += "fortunesToCreate=" + encodeURIComponent("" + fortunesToCreate) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateFortunes(_response);
        });
    }

    protected processCreateFortunes(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(null as any);
    }

    /**
     * @param fortunesToGet (optional) 
     * @return OK
     */
    getFortunes(fortunesToGet: number | undefined): Promise<FortuneModel[]> {
        let url_ = this.baseUrl + "/Fortune/get?";
        if (fortunesToGet === null)
            throw new Error("The parameter 'fortunesToGet' cannot be null.");
        else if (fortunesToGet !== undefined)
            url_ += "fortunesToGet=" + encodeURIComponent("" + fortunesToGet) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetFortunes(_response);
        });
    }

    protected processGetFortunes(response: Response): Promise<FortuneModel[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(FortuneModel.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FortuneModel[]>(null as any);
    }

    /**
     * @return OK
     */
    getRandom(): Promise<FortuneModel> {
        let url_ = this.baseUrl + "/Fortune/getRandom";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetRandom(_response);
        });
    }

    protected processGetRandom(response: Response): Promise<FortuneModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FortuneModel.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FortuneModel>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    generateFortunes(body: string[] | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Fortune/generate";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGenerateFortunes(_response);
        });
    }

    protected processGenerateFortunes(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(null as any);
    }
}

export class FortuneModel implements IFortuneModel {
    id?: string;
    longFortune?: string | undefined;
    shortFortune?: string | undefined;
    imageTopics?: string | undefined;
    qrImage?: string | undefined;
    audio?: string | undefined;
    fortuneImage?: string | undefined;
    luckyNumbers?: number[] | undefined;
    fortuneUsed?: boolean;
    fortuneType?: string | undefined;

    constructor(data?: IFortuneModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.longFortune = _data["longFortune"];
            this.shortFortune = _data["shortFortune"];
            this.imageTopics = _data["imageTopics"];
            this.qrImage = _data["qrImage"];
            this.audio = _data["audio"];
            this.fortuneImage = _data["fortuneImage"];
            if (Array.isArray(_data["luckyNumbers"])) {
                this.luckyNumbers = [] as any;
                for (let item of _data["luckyNumbers"])
                    this.luckyNumbers!.push(item);
            }
            this.fortuneUsed = _data["fortuneUsed"];
            this.fortuneType = _data["fortuneType"];
        }
    }

    static fromJS(data: any): FortuneModel {
        data = typeof data === 'object' ? data : {};
        let result = new FortuneModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["longFortune"] = this.longFortune;
        data["shortFortune"] = this.shortFortune;
        data["imageTopics"] = this.imageTopics;
        data["qrImage"] = this.qrImage;
        data["audio"] = this.audio;
        data["fortuneImage"] = this.fortuneImage;
        if (Array.isArray(this.luckyNumbers)) {
            data["luckyNumbers"] = [];
            for (let item of this.luckyNumbers)
                data["luckyNumbers"].push(item);
        }
        data["fortuneUsed"] = this.fortuneUsed;
        data["fortuneType"] = this.fortuneType;
        return data;
    }
}

export interface IFortuneModel {
    id?: string;
    longFortune?: string | undefined;
    shortFortune?: string | undefined;
    imageTopics?: string | undefined;
    qrImage?: string | undefined;
    audio?: string | undefined;
    fortuneImage?: string | undefined;
    luckyNumbers?: number[] | undefined;
    fortuneUsed?: boolean;
    fortuneType?: string | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}